In [4]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기',
         '믹서','믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
print(labels)
print('인코딩 변환값:', labels)

[0 1 4 5 3 3 2 2]
인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자랜지' '컴퓨터']


In [6]:
print('디코딩 원본 값:', encoder.inverse_transform([0,1,4,5,3,3,2,2]))

디코딩 원본 값: ['TV' '냉장고' '전자랜지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [10]:
# 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items = ['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기',
         '믹서','믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)
labels

oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print('원-핫 인코딩:')
print(oh_labels.toarray())

원-핫 인코딩:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [ ]:
# 과제
# Q. itesms를 pd.get_dummies()를 사용하여 원핫인코딩 하세요
# items = ['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기',
#          '믹서','믹서']

In [ ]:
# 과제
# Q. 붓꼿 데이터 셋의 독립변수들을 2가지 방법으로 스케일링 한 후 
# 평균 값과 분산 값을 출력하세요.
# - 0과 1사이의 범위로 스케일링
# - 평균 0, 표준편차 1인 분포로 스케일링