In [18]:
# 파이썬 ramdom 함수
import random
# print(random.random())             # 0.0<= x <1.0 사이
# print(random.randint(1,10))        # 1에서 10사이의 정수중에서 난수값 리턴
# print(random.uniform(10,20))       # min max 사이 float 리턴
# print(random.randrange(10))        # 지정범위 int 리턴
# print(random.choice([1,2,3,4,5]))  # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
# print(random.sample(li,5))         # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li)                   # 리스트 요소를 다시 섞어서 리턴
print(li)

[4, 2, 3, 1, 5]
[3, 5, 4, 1, 2]


In [ ]:
# 넘파이의 np.random
# rand : 0.0 ~ 1.0 사이의 균일 분포
# randn : 가우시안 표준 정규 분포
# randint : 균일 분포의 정수 난수

In [25]:
# 0.0 ~ 1.0 사이의 균일 분포인 실수
import numpy as np
np.random.seed(0)
np.random.rand(5)
np.random.rand(3,2)

array([[0.64589411, 0.43758721],
       [0.891773  , 0.96366276],
       [0.38344152, 0.79172504]])

In [24]:
np.random.randint(5) # 0 ~ 4까지 정수 난수 1개
np.random.randint(1,20)
np.random.randint(10, size=10)
np.random.randint(10,20,size=10)
np.random.randint(10,20,size=(3,5))

array([[12, 10, 13, 15, 19],
       [14, 14, 16, 14, 14],
       [13, 14, 14, 18, 14]])

In [35]:
np.random.choice([1,2,3,4,5])
# np.random.choice(5,5,replace=False)
np.random.choice(5,5)

array([0, 1, 1, 1, 1])

In [39]:
list = [0,1,2,3,4]
np.random.shuffle(list)
# np.random.choice(5,5,replace=False)
list

[0, 1, 2, 3, 4]

In [41]:
np.random.randn(6)
np.random.randn(3,2)

array([[-0.3756659 , -0.03822364],
       [ 0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ]])

In [45]:
# 범위내 실수 출력
np.random.uniform(1,2,3)
np.random.uniform(0,1,(2,3))

array([[0.26473016, 0.39782075, 0.55282148],
       [0.16494046, 0.36980809, 0.14644176]])

In [44]:
# random_sample은 uniform 하수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.50896896, 0.91672295, 0.92115761],
       [0.08311249, 0.27771856, 0.0093567 ]])

## 과제
### Q. 고객 구매데이터 생성(id, 성별, 연령, 지역, 상품, 가격, 구매시간) 하고 데이터 프레임으로 변환한 후 아래 사항을 수행하세요.
#### 구매 데이터 생성
- id : 1번 ~ 1000번 일련번호(관측치 1000개)
- gender : 0,1 정수 난수 생성
- age : 10 ~ 80사이 정수 난수를 생성하고 범주화하여 age_cat 파생
- region : 1 ~ 10 사이 정수 난수 생성
- product : 1개 제품 이상
- price_avg_19 : 1000 ~ 50000 사이 실수 난수 생성하고 범주화하여 price_avg_cat 파생
- price_avg_20 : 1000 ~ 50000 사이 실수 난수 생성하고 범주화하여 price_avg_cat 파생
- qty_19 : 1 ~ 100 사이 정수 난수 생성하여('19년 구매 수량) 
- qty_20 : 1 ~ 100 사이 정수 난수 생성하여('20년 구매 수량)
- time_19 : 01 ~ 24 사이 정수 난수 생성하고 오전, 오후, 야간 으로 범주화하여 time_cat_19 파생('19년에 가장 자주 구매한 시간대)
- time_20 : 01 ~ 24 사이 정수 난수 생성하고 오전, 오후, 야간 으로 범주화하여 time_cat 파생('20년에 가장 자주 구매한 시간대)
- 구매액은 price * qty로 산출('19년, '20년 각각 계산)하여 pur_19, pur_20 컬럼으로 생성 
- 종속변수(결과변수)는 (pur_20 - pur_19)으로 계산하여 구매액 증감을 0(감소), 1(증가)로 범주화하여 pur_gap 컬럼 생성
- np.nan으로 각 컬럼별로 10개씩 null값을 삽입하고 각 칼럼의 특성을 고려한 null 값 처리

#### 인사이트 도출
- 통계적 분석 및 시각화하여 탐색한 후 불필요한 컬럼은 삭제하고 필요시 추가 파생변수 생성한 후 분석용 데이터셋을 작성하고 인사이트 3개 이상 도출
- 인사이트 도출하지 못한 경우 데이터를 수정하여 다시 탐색한 후 인사이트 도출 및 기술

#### 데이터 수정시 참조
- 구매액 증감에 영향을 주는 주요 요인과 관련된 인사이트를 만들 수 있는 데이터로 변경하는 점에 중점을 둠
- 구매 감소한 고객의 특성으로 성별, 지역, 선호제픔, 선호 구매시간대, 평균 구매가 level(저가, 중가, 고가)별로 데이터 수정
- 연령, 성별로 상품유형, 구매단가, 구매시간대 등을 복합적으로 그룹화하여 데이터 특성 부여
- 연도별로 상기한 사항들의 변동과 구매 감소간의 상관성을 부여하는 데이터 수정
- 데이터 수정은 불린 인덱싱으로 특정 그룹을 선택한 후 고객 특성에 맞는 값으로 변경