<a href="https://colab.research.google.com/github/bnv20/cakd3/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98%20%EA%B5%AC%ED%98%84/dl_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x = np.array([1,2,3])

In [ ]:
x.__class__

numpy.ndarray

In [ ]:
# shape : 다차원 배열의 형상
x.shape

(3,)

In [ ]:
# ndim : 차원 수
x.ndim

1

In [ ]:
w = np.arange(1,7).reshape(2,3)
w.shape

(2, 3)

In [ ]:
w.ndim

2

In [ ]:
# 행렬의 원소별 연산
W = np.arange(1,7).reshape(2,3)
X = np.arange(6).reshape(2,3)
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [ ]:
# 브로드캐스트
A = np.arange(1,5).reshape(2,2)
A * 10

array([[10, 20],
       [30, 40]])

In [ ]:
A = np.arange(1,5).reshape(2,2)
b = np.array([10,20])
A * b

array([[10, 40],
       [30, 80]])

벡터와 행렬의 연산 : https://datascienceschool.net/02%20mathematics/02.02%20%EB%B2%A1%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.html

In [ ]:
# 행렬의 곱
# 넘파이에서 벡터와 행렬의 내적은 dot()이라는 명령 또는 @(at이라고 읽는다)이라는 연산자로 계산한다. 2차원 배열로 표시한 벡터를 내적했을 때는 결과값이 스칼라가 아닌 2차원 배열
import numpy as np
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])
print(x,'\n')
print(y)
print(x.T)
np.dot(x.T,y)
# x.T@y

[[1]
 [2]
 [3]] 

[[4]
 [5]
 [6]]
[[1 2 3]]


array([[32]])

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.matmul(x,y)
print(x,'\n')
print(x.T,'\n')
print(np.dot(x,y),'\n')
print(np.dot(x.T,y))

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]] 

[[19 22]
 [43 50]] 

[[26 30]
 [38 44]]


In [ ]:
# 벡터의 내적
# 넘파이에서는 1차원 배열끼리도 내적을 계산한다. 이때는 넘파이가 앞의 벡터는 행 벡터이고 뒤의 벡터는 열 벡터라고 가정
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x)
print(y)
print(np.dot(x,y))
# x@y
print(np.dot(x.T,y))

[1 2 3]
[4 5 6]
32
32


In [ ]:
# 대각 행렬
import numpy as np
print(1+np.arange(4))
z = np.diag(1+np.arange(4),k=0)
z

[1 2 3 4]


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
import numpy as np
x = np.random.randn(10,2) # (10,2)
W1 = np.random.randn(2,4) # (2,4) 
b1 = np.random.randn(4)
h = np.matmul(x,W1) + b1
print(x,'\n')
print(W1,'\n')
print(b1,'\n')
h

[[ 1.07009536 -0.74802875]
 [ 0.20017814  2.63444909]
 [ 1.09058625  0.58155289]
 [-0.42522788  0.38338053]
 [ 0.63038761  0.44019293]
 [ 1.52011254 -1.1878602 ]
 [ 0.43441376  0.82846918]
 [-0.46844803  1.49982254]
 [ 1.86855151 -1.09671943]
 [-0.81296632 -0.5448657 ]] 

[[ 1.35465846 -0.84272471  0.28581423 -0.10599414]
 [ 1.74887925  1.19288307 -0.93936874 -0.56138565]] 

[-0.30741095  0.3484758  -0.04971604  0.28713161] 



array([[-0.16600918, -1.44563083,  0.95880727,  0.59364037],
       [ 4.57109541,  3.32237046, -2.4672214 , -1.21302801],
       [ 2.18702672,  0.12313642, -0.28430358, -0.15493959],
       [-0.21296325,  1.16415399, -0.53138791,  0.11697895],
       [ 1.31639324,  0.34233128, -0.28304577, -0.02680378],
       [-0.3256017 , -2.34953892,  1.5005925 ,  0.79285625],
       [ 1.72996388,  0.97065144, -0.70379245, -0.22400441],
       [ 1.6810105 ,  2.53236145, -1.59249157, -0.50519449],
       [ 0.30580829, -2.53445678,  1.51456653,  0.70475865],
       [-2.36160698,  0.38362154,  0.22975643,  0.67918107]])

In [ ]:
# 완전연결계층에 의한 변환은 선형 변환인 반면 '비선형 효과를 부여하는 것이 활성화 함수
# 시그모이드 함수 : 임의의 실수를 입력받아 0에서 1사이의 실수를 반환

def sigmoid(x):
  return 1 / ( 1 + np.exp(-x))

a = sigmoid(h)
a

array([[0.45859276, 0.1906749 , 0.72288294, 0.64419998],
       [0.98975934, 0.96518833, 0.07818827, 0.22916572],
       [0.89907844, 0.53074527, 0.42939901, 0.46134241],
       [0.4469595 , 0.7620867 , 0.37019324, 0.52921143],
       [0.78858101, 0.58475671, 0.42970722, 0.49329946],
       [0.41931118, 0.08710243, 0.81766283, 0.68844429],
       [0.8494078 , 0.72524933, 0.33097193, 0.4442319 ],
       [0.84303829, 0.92637957, 0.16903364, 0.37632072],
       [0.57586178, 0.07347766, 0.81973698, 0.66924198],
       [0.0861476 , 0.59474628, 0.55718776, 0.6635559 ]])

In [ ]:
# x의 형상 (10,2), 최종 출력인 s의 형상은 (10,3)
# 10개의 데이터가 한꺼번에 처리되었고 각 데이터는 3차원 데이터로 변환됨
# 각 차원의 값을 이용하여 3 클래스 분류 수행. 출력된 각 차원은 각 클래스에 대응하는 점수
# 실제로 분류를 하면 출력층에서 가장 큰 값을 보여주는 뉴런에 해당하는 클래스가 예측 결과가 된다.
import numpy as np
x = np.random.randn(10,2) # (10,2)
W1 = np.random.randn(2,4) # (2,4) 
b1 = np.random.randn(4)

W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x,W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2
print(a,'\n')
print(W2,'\n')
print(b2,'\n')
print(s)

[[0.22662351 0.78819635 0.72005048 0.90849412]
 [0.22032094 0.68688021 0.87143223 0.70471832]
 [0.37098877 0.8310244  0.8603324  0.98110143]
 [0.42353606 0.88733968 0.79181003 0.99579914]
 [0.31708423 0.81361424 0.82728383 0.965163  ]
 [0.15371323 0.52676184 0.91316772 0.18478635]
 [0.42204245 0.79559501 0.93786416 0.97399721]
 [0.36584324 0.64689098 0.97637718 0.79359675]
 [0.13037299 0.61640352 0.77520287 0.31391855]
 [0.36053866 0.7642152  0.9275176  0.9428473 ]] 

[[ 1.30668295e-03  3.05092338e-01  8.10245818e-01]
 [ 6.88933209e-01  1.06226952e+00 -4.21917792e-01]
 [-1.56238895e-01 -1.63612219e+00 -1.03109656e+00]
 [-2.06543568e-02 -1.12080183e+00 -1.51809984e+00]] 

[0.16096142 0.44118632 0.63117988] 

[[ 0.57300793 -0.84872806 -1.63937977]
 [ 0.48375678 -0.97756274 -1.44847653]
 [ 0.57928509 -1.07008516 -1.7953477 ]
 [ 0.6285535  -0.89859364 -1.72819131]
 [ 0.57271288 -1.03308999 -1.77340557]
 [ 0.37757704 -0.65351676 -0.68861303]
 [ 0.54297658 -1.21103365 -1.8081912 ]
 [ 0.43816

In [ ]:
# + 연산자는 리스트를 결합
a = ['A','B']
a += ['C','D']
a

['A', 'B', 'C', 'D']

오차역전파법 : https://deep-learning-study.tistory.com/18

In [ ]:
# 입력 데이터 x에 대한 점수(s)를 도출
# 어파인 변환(affine transformation)은 신경망 순전파 때 수행하는 행렬의 곱을 기하학에서 부르는 이름입니다. 
# 어파인 변환을 수행하는 처리를 'Affine'계층 이라는 이름으로 구현
# coding: utf-8
import numpy as np

class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))

class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[-0.01548227 -0.85746952 -0.71468238]
 [-0.01617994 -0.85474196 -0.71926361]
 [-0.08196978 -0.49171307 -0.99569699]
 [-0.03590128 -0.74928466 -0.80056424]
 [ 0.17878753 -1.83770643  0.15745123]
 [-0.2603716   0.27694838 -1.70485955]
 [-0.00555661 -0.9565083  -0.59818357]
 [ 0.07723278 -1.35303519 -0.26808887]
 [-0.20366055  0.08210232 -1.5196958 ]
 [ 0.21076525 -1.89728964  0.18614705]]


In [ ]:
import numpy as np
D,N=8,7
x = np.random.randn(1,D)
y = np.repeat(x, N, axis=0) # 순전파
dy = np.random.randn(N,D)
dx = np.sum(dy,axis=0, keepdims=True) # 역전파
print(x,'\n')
print(y,'\n')
print(dy,'\n')
dx

[[-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]] 

[[-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]
 [-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]
 [-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]
 [-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]
 [-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]
 [-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]
 [-1.60324712 -0.34500018 -1.57598225  0.03125475  0.17804284  0.45145712
  -1.54330074 -0.89069685]] 

[[-0.94549073  0.72174531 -0.06414223  0.46418085 -0.16960443 -0.78103233
  -1.09882873 -0.62982712]
 [-1.74284378  0.34741456  0.80635323  1.95542689 -0.26648036  0.28032904
  -0.812228

array([[ 0.4044892 , -1.05838976,  1.75783377, -2.27546841,  0.37261994,
        -5.89575281, -2.46740453,  1.32531184]])

In [ ]:
import numpy as np
D,N=8,7
x = np.random.randn(N,D)
y = np.sum(x, axis=0, keepdims=True) # 2차원 배열의 차원 수 유지, 순전파
dy = np.random.randn(1,D)
dx = np.repeat(dy,N, axis=0) # 역전파
print(x,'\n')
print(y,'\n')
print(dy,'\n')
dx

[[-0.55507248 -0.59622093  2.74362098 -1.3197828  -0.1597511  -2.40682901
   0.23473893  0.19116275]
 [-0.4541125  -1.2323671  -0.81910583 -1.79925584 -0.32964541  0.4548777
  -1.45540176  0.3139226 ]
 [ 0.11892685 -0.43342989 -0.37048607  0.70203403 -0.25446656 -0.25113857
   1.36983652 -0.72229295]
 [ 0.69670845  0.64037641  0.43767146  0.2401948   1.05149022 -0.75763872
   0.12164326  0.03069671]
 [ 1.11862079 -1.35147652  1.61604017 -0.51477204  0.05373985  0.35408918
  -0.98561528 -0.46346739]
 [-0.62876894  0.41607393 -0.49588276  0.2768972  -0.2552704   0.56712621
  -0.01377866 -2.36910619]
 [-0.2241953  -0.14966456  0.2929398  -0.30772187 -0.23386472 -1.2887175
  -0.35253286 -1.1248174 ]] 

[[ 0.07210688 -2.70670865  3.40479776 -2.72240652 -0.12776813 -3.32823072
  -1.08110984 -4.14390187]] 

[[-1.07079558 -1.15984075 -1.26313698  0.75425669 -0.77257982 -1.00712305
  -0.20350133 -1.37439778]] 



array([[-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778],
       [-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778],
       [-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778],
       [-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778],
       [-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778],
       [-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778],
       [-1.07079558, -1.15984075, -1.26313698,  0.75425669, -0.77257982,
        -1.00712305, -0.20350133, -1.37439778]])

np.dot과 np.matmul의 차이 : 
- https://jlog1016.tistory.com/80 
- https://cyber0946.tistory.com/64


In [ ]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx